version: '3'

services:
  nginx:
    build: .
    container_name: jorgedev_net
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/usr/share/nginx/html:/usr/share/nginx/html
      - ./nginx/etc/nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot_jorgedev
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web

networks:
  web:
    driver: bridge